title: Notion Parallax
email: ben@notionparallax.co.uk
description: > # this means to ignore newlines until "baseurl:"
    This is where I write things down. It's the way I make space in my
    head for new ideas. The ideas here were what I thought at the time,
    but there is a very good chance that I no longer think that!
baseurl: "/blogTemplate" # the subpath of your site, e.g. /blog. If this is on ghpages then it's the repo name
url: "https://notionparallax.github.io" # the base hostname & protocol for your site

#google analytics
GAcode: UA-52654925-12

author:
  display_name: Ben
  first_name: Ben
  last_name: Doherty
twitter_username: notionparallax
github_username:  notionparallax
author-facebook:  ben.doherty1
#schema.org data
name:         Ben Doherty
facebookURL:  ben.doherty1          # ignore the https://www.facebook.com/ part
instagramURL: Pigsu_                # ignore the http://instagram.com/ part
linkedInURL:  ben-doherty-b2a19359" # ignore the https://ca.linkedin.com/in/ part

# Build settings
markdown: kramdown
permalink: "/:year/:title"

kramdown:
  parse_block_html: true
